<?php

$username = "mitch@study.net";
$password = "Ve&@p57KW";
$company = "STX-02244-01";
/*
Change for production: $wsdl = 'https://service.myspeedtax.com/tx/services/STxTransactionService?wsdl';
*/
$wsdl = 'https://service.myspeedtax.com/tx/services/STxTransactionService?wsdl';
//       https://service.myspeedtax.com/tx/services/STxTransactionService

//$wsdl = 'http://service.demo.myspeedtax.com/tx/services/STxTransactionService?wsdl';

?>